/**
 * 
 */
package test;

import static org.junit.Assert.*;

import org.junit.Test;

import core.partsModule.models.PartItem;
import core.partsModule.models.PartsTableModel;
import core.settings.models.AppPreferences;

/**
 * @author hgv265
 *
 */
public class Assignment2TestCases {

     /**
     * Test to see if a part object contains all elements
     * 
     */
    @Test
    public void testPartID() {
        PartsTableModel model = new PartsTableModel(new AppPreferences());
        PartItem newPart = new PartItem(0, "testno", "testnoext", "testname", "testven", "testqunit");

        int newPartID = 0;
        boolean autoID = false;

    	model.addRow(newPart);
    	for(int i =0; i < model.getRows().size(); i++){
    		if(model.getRow(i).getPartName().equals(newPart.getPartName())){
    			newPartID = model.getRow(i).getPartID();
    			model.removeRow(model.getRow(i));
    			if(newPartID != 0) autoID = true;
    			model.exitModule();
    			break;
    		}
    	}
    	
        assertTrue("PartID should be autogenerated and unique", autoID);
    }

     /**
     * Test to see if a part now includes unit of quantity field is created correctly
     * 
     */
    @Test
    public void testPartUofQ() {
        boolean exists = false;
        PartItem newPart = null;
        try {
        	newPart = new PartItem();
        	System.out.println(newPart.getPartQuantityUnit());
        	exists = true;
        } catch (NullPointerException e) {
            exists = false;
        }
        assertTrue("Part does not contain Unit of Quantity Field.", exists);
    }
    
     /**
     * Test to see if a part now includes external number field is created correctly
     * 
     */
    @Test
    public void testPartNoExternal() {
    	boolean exists = false;
        PartItem newPart = null;
        try {
        	newPart = new PartItem();
        	System.out.println(newPart.getPartNoExternal());exists = true;
        } catch (NullPointerException e) {
            exists = false;
        } 
        assertTrue("Part does not contain External Part Number Field.", exists);
    }
    
}
